const ActionTypes = {
  SET_IS_ALERT_VISIBLE: "SET_IS_ALERT_VISIBLE",
  SET_ALERT_TEXT: "SET_ALERT_TEXT",
  SET_IS_SUCCESS_MESSAGE_VISIBLE: "SET_IS_SUCCESS_MESSAGE_VISIBLE",
  SET_SUCCESS_MESSAGE_TEXT: "SET_SUCCESS_MESSAGE_TEXT:",
  SET_USER_DATA: "SET_USER_DATA",
  SET_USER_CARS: "SET_USER_CARS",
  SET_LOCATIONS: "SET_LOCATIONS",
  SET_HAS_USER_SIGN_UP: "SET_HAS_USER_SIGN_UP",
  SET_USER_RESERVATIONS: "SET_USER_RESERVATIONS",
  SET_DISPLAY_MODAL: "SET_DISPLAY_MODAL",
  SET_DISPLAY_MODAL_TEXT: "SET_DISPLAY_MODAL_TEXT",
  SET_USER_REPORTS: "SET_USER_REPORTS",
  CLEAR_USER_DATA: "CLEAR_USER_DATA",
  SET_HARDWARE_NUMBER_OF_CARS: "SET_HARDWARE_NUMBER_OF_CARS",
};

export default ActionTypes;
